### ISSUE TITLE
Extra apostrophe in require_relative statement in spec

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-password-security#21]
```
D, [2016-03-21T19:47:21.894337 #3761] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
/Users/yonk/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load': /Users/yonk/Development/code/sinatra-password-security-v-000/spec/create_users_migration_spec.rb:3: syntax error, unexpected tIDENTIFIER, expecting end-of-input (SyntaxError)
require_relative 'spec_helper'
                             ^
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[19:47:21] (master) sinatra-password-security-v-000
```
```ruby
# ./spec/create_users_migration_spec
require_relative '../db/migrate/20150916154312_create_users.rb''
```

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/sinatra-password-security/commit/24d81c8bb29447ddb604abd582e9362364180377
